  --zadachi week one
  --1
  SELECT ADDRESS FROM STUDIO
  WHERE NAME = 'Disney'

  --2
  SELECT BIRTHDATE FROM MOVIESTAR
  WHERE NAME = 'Jack Nicholson'

  --3
  SELECT STARNAME FROM STARSIN
  WHERE MOVIEYEAR = 1980 OR MOVIETITLE LIKE '%Knight%' 

  --4
  SELECT NAME FROM MOVIEEXEC
  WHERE NETWORTH > 10000000
  
  --5
  SELECT NAME FROM MOVIESTAR
  WHERE GENDER = 'M' OR ADDRESS = 'Prefect Rd.'

  --6
SELECT MODEL,SPEED AS MHz, HD AS GB FROM PC 

--7
SELECT DISTINCT MAKER FROM PRODUCT
WHERE TYPE = 'Printer'

--8
SELECT MODEL,RAM,SCREEN FROM LAPTOP
WHERE PRICE > 1000

--9
SELECT * FROM PRINTER
WHERE COLOR = 'y'

--10
SELECT MODEL,SPEED,HD FROM PC
WHERE (CD = '12x' OR CD = '16x') OR PRICE < 2000

--11
SELECT CLASS, COUNTRY FROM CLASSES
WHERE NUMGUNS < 10

--12
SELECT NAME AS SHIPNAME FROM SHIPS 
WHERE LAUNCHED < 1918

--13
SELECT SHIP, BATTLE FROM OUTCOMES
WHERE RESULT = 'sunk'

--14
SELECT NAME FROM SHIPS
WHERE NAME = CLASS

--15
SELECT NAME FROM SHIPS
WHERE NAME LIKE 'R%'

--16
SELECT NAME FROM SHIPS
WHERE LEN(NAME) - LEN(REPLACE(NAME, ' ', '')) >= 1
