 --zadachi week two
 --1
 SELECT NAME FROM MOVIESTAR
 JOIN STARSIN ON MOVIESTAR.NAME = STARSIN.STARNAME
 WHERE GENDER = 'M' AND MOVIETITLE = 'The Usual Suspects'

 --2
 SELECT STARNAME FROM STARSIN
 JOIN MOVIE ON STARSIN.MOVIETITLE = MOVIE.TITLE
 WHERE STUDIONAME = 'MGM' AND MOVIEYEAR = 1995

 --3
 SELECT DISTINCT NAME FROM MOVIEEXEC
 JOIN MOVIE ON MOVIEEXEC.CERT#= MOVIE.PRODUCERC#
 WHERE STUDIONAME = 'MGM'

 --4
 SELECT TITLE FROM MOVIE
 WHERE LENGTH > (SELECT LENGTH FROM MOVIE 
 WHERE TITLE = 'Star Wars')
 
 --5
 SELECT NAME FROM MOVIEEXEC 
 WHERE NETWORTH > (SELECT NETWORTH FROM MOVIEEXEC
 WHERE NAME = 'Stephen Spielberg')
--6
SELECT MAKER, SPEED FROM PRODUCT
JOIN LAPTOP ON LAPTOP.MODEL = PRODUCT.MODEL
WHERE LAPTOP.HD > 9 

--7
SELECT LAPTOP.MODEL, PRICE FROM PRODUCT
JOIN LAPTOP ON LAPTOP.MODEL = PRODUCT.MODEL
WHERE MAKER = 'B'
UNION
SELECT PC.MODEL, PRICE FROM PRODUCT
JOIN PC ON PC.MODEL = PRODUCT.MODEL
WHERE MAKER = 'B'
UNION
SELECT PRINTER.MODEL, PRICE FROM PRODUCT
JOIN PRINTER ON PRINTER.MODEL = PRODUCT.MODEL
WHERE MAKER = 'B'

--8
SELECT MAKER FROM PRODUCT
JOIN LAPTOP ON LAPTOP.MODEL = PRODUCT.MODEL
WHERE MAKER NOT IN (SELECT MAKER FROM PRODUCT
WHERE TYPE = 'PC')

SELECT MAKER FROM PRODUCT
WHERE TYPE = 'Laptop' AND MAKER NOT IN (SELECT MAKER FROM PRODUCT
WHERE TYPE = 'PC')

--9
SELECT DISTINCT HD FROM PC one
WHERE (SELECT COUNT(MODEL) FROM PC two
WHERE two.HD = one.HD) >= 2

--10
SELECT ONE.MODEL, TWO.MODEL FROM PC ONE
JOIN PC TWO ON ONE.SPEED = TWO.SPEED 
AND ONE.RAM = TWO.RAM
AND ONE.MODEL < TWO.MODEL

--11
SELECT MAKER FROM PRODUCT
JOIN PC ON PC.MODEL = PRODUCT.MODEL
WHERE SPEED >= 400
GROUP BY MAKER
HAVING COUNT(PC.MODEL) >= 2

--12
SELECT NAME FROM SHIPS
JOIN CLASSES ON SHIPS.CLASS = CLASSES.CLASS
WHERE DISPLACEMENT > 50000

--13
SELECT NAME, DISPLACEMENT, NUMGUNS FROM CLASSES
JOIN SHIPS ON CLASSES.CLASS = SHIPS.CLASS
JOIN OUTCOMES ON OUTCOMES.SHIP = SHIPS.NAME
WHERE BATTLE = 'Guadalcanal'

--14
SELECT COUNTRY FROM CLASSES
GROUP BY COUNTRY
HAVING (COUNT(DISTINCT TYPE) >= 2)

--15
SELECT SHIP FROM OUTCOMES
JOIN BATTLES B1 ON B1.NAME = OUTCOMES.BATTLE
WHERE RESULT = 'damaged' AND SHIP IN (SELECT SHIP FROM OUTCOMES 
JOIN BATTLES B2 ON B2.NAME = OUTCOMES.BATTLE
WHERE B1.DATE < B2.DATE) 
